### ISSUE TITLE
mozjpeg build failed on mac [solved]

### ISSUE THREAD

**Issue by mos200** [JeffreyWay/laravel-mix#1271]
any one can help me please 
i got this error when i install npm on any laravel project 

> mozjpeg@4.1.1 postinstall /Applications/XAMPP/xamppfiles/htdocs/blog/node_modules/mozjpeg
> node lib/install.js

  ⚠ The `/Applications/XAMPP/xamppfiles/htdocs/blog/node_modules/mozjpeg/vendor/cjpeg` binary doesn't seem to work correctly
  ⚠ mozjpeg pre-build test failed
  ℹ compiling from source
  ✖ Error: autoreconf -fiv && ./configure --disable-shared --prefix="/Applications/XAMPP/xamppfiles/htdocs/blog/node_modules/mozjpeg/vendor" --bindir="/Applications/XAMPP/xamppfiles/htdocs/blog/node_modules/mozjpeg/vendor" --libdir="/Applications/XAMPP/xamppfiles/htdocs/blog/node_modules/mozjpeg/vendor" && make --jobs=4 && make install --jobs=4
Command failed: autoreconf -fiv
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force 
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/local/bin/autoconf --force
configure.ac:22: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/local/bin/autoconf failed with exit status: 1

    at ChildProcess.exithandler (child_process.js:198:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)

> optipng-bin@3.1.4 postinstall /Applications/XAMPP/xamppfiles/htdocs/blog/node_modules/optipng-bin
> node lib/install.js

  ⚠ getaddrinfo ENOTFOUND raw.githubusercontent.com raw.githubusercontent.com:443
  ⚠ optipng pre-build test failed
  ℹ compiling from source
  ✖ Error: ./configure --with-system-zlib --prefix="/Applications/XAMPP/xamppfiles/htdocs/blog/node_modules/optipng-bin/vendor" --bindir="/Applications/XAMPP/xamppfiles/htdocs/blog/node_modules/optipng-bin/vendor" && make install
Command failed: make install
pngrtran.c:98:1: warning: unused function 'png_rtran_ok' [-Wunused-function]
png_rtran_ok(png_structrp png_ptr, int need_IHDR)
^
1 warning generated.
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libpng.a(pngpread.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libpng.a(pngwtran.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libpng.a(pngpread.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libpng.a(pngwtran.o) has no symbols
pngxmem.c:37:32: warning: comparison of constant 2305843009213693951 with expression of type 'png_uint_32' (aka 'unsigned int') is always false [-Wtautological-constant-out-of-range-compare]
   if (row_size == 0 || height > (pngx_alloc_size_t)(-1) / sizeof(png_bytep))
                        ~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libpngxtern.a(pngxio.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libpngxtern.a(pngxio.o) has no symbols
osys.c:515:25: error: no member named 'st_atim' in 'struct stat'
        times[0] = sbuf.st_atim;
                   ~~~~ ^
osys.c:516:25: error: no member named 'st_mtim' in 'struct stat'
        times[1] = sbuf.st_mtim;
                   ~~~~ ^
2 errors generated.
make[1]: *** [osys.o] Error 1
make: *** [install] Error 2

    at ChildProcess.exithandler (child_process.js:198:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Socket.<anonymous> (internal/child_process.js:351:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:497:12)

> pngquant-bin@3.1.1 postinstall /Applications/XAMPP/xamppfiles/htdocs/blog/node_modules/pngquant-bin
> node lib/install.js

**Comment by ruchern** [comment]
What is your npm version?

**Comment by mos200** [comment]
npm 3.10.10
node v6.11.4

**Comment by ruchern** [comment]
Update the versions. It’s too old.

**Comment by mos200** [comment]
ok now i updated to 
node    v8.7.0
npm     5.4.2
 i make 
`rm -rf node_modules && npm cache clear && npm install`.
and also i get this error 


> mozjpeg@4.1.1 postinstall /Applications/XAMPP/xamppfiles/htdocs/blog/node_modules/mozjpeg
> node lib/install.js

  ⚠ The `/Applications/XAMPP/xamppfiles/htdocs/blog/node_modules/mozjpeg/vendor/cjpeg` binary doesn't seem to work correctly
  ⚠ mozjpeg pre-build test failed
  ℹ compiling from source
  ✖ Error: autoreconf -fiv && ./configure --disable-shared --prefix="/Applications/XAMPP/xamppfiles/htdocs/blog/node_modules/mozjpeg/vendor" --bindir="/Applications/XAMPP/xamppfiles/htdocs/blog/node_modules/mozjpeg/vendor" --libdir="/Applications/XAMPP/xamppfiles/htdocs/blog/node_modules/mozjpeg/vendor" && make --jobs=4 && make install --jobs=4
Command failed: autoreconf -fiv
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force 
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/local/bin/autoconf --force
configure.ac:22: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/local/bin/autoconf failed with exit status: 1

    at ChildProcess.exithandler (child_process.js:271:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

**Comment by ankurk91** [comment]
I suspect this is related to x-code.

**Comment by mos200** [comment]
@ankurk91 @ruchern
i update the x-code to Version 9.0 and still i have same issue :(  ⚠ The `/Applications/XAMPP/xamppfiles/htdocs/blog/node_modules/mozjpeg/vendor/cjpeg` binary doesn't seem to work correctly
  ⚠ mozjpeg pre-build test failed
  ℹ compiling from source
  ✖ Error: autoreconf -fiv && ./configure --disable-shared --prefix="/Applications/XAMPP/xamppfiles/htdocs/blog/node_modules/mozjpeg/vendor" --bindir="/Applications/XAMPP/xamppfiles/htdocs/blog/node_modules/mozjpeg/vendor" --libdir="/Applications/XAMPP/xamppfiles/htdocs/blog/node_modules/mozjpeg/vendor" && make --jobs=4 && make install --jobs=4
Command failed: autoreconf -fiv
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force 
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/local/bin/autoconf --force
configure.ac:22: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/local/bin/autoconf failed with exit status: 1

    at ChildProcess.exithandler (child_process.js:271:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

> optipng-bin@3.1.4 postinstall /Applications/XAMPP/xamppfiles/htdocs/blog/node_modules/optipng-bin
> node lib/install.js

**Comment by ankurk91** [comment]
Can you try
```
brew update
brew install libtool
```
One of user has [suggested](https://github.com/imagemin/imagemin/issues/168#issuecomment-314313374) this
```
brew install automake autoconf libtool dpkg pkgconfig nasm libpng
```

**Comment by mos200** [comment]
brew install automake autoconf libtool dpkg pkgconfig nasm libpng

finally work with me thank you so much 
i reinstall the hole system two time for this error 😡
thank you so much @ankurk91

**Comment by kkxiaoa** [comment]
> Can you try
> 
> ```
> brew update
> brew install libtool
> ```
> 
> One of user has [suggested](https://github.com/imagemin/imagemin/issues/168#issuecomment-314313374) this
> 
> ```
> brew install automake autoconf libtool dpkg pkgconfig nasm libpng
> ```

Thanks, my problem is solved ！😊

**Comment by lisandropat** [comment]
Problem persist:

`npm ERR! code 1
npm ERR! path /Users/lisandropat/src/zala/node_modules/mozjpeg
npm ERR! command failed
npm ERR! command sh -c node lib/install.js
npm ERR! ⚠ spawn Unknown system error -86
npm ERR!   ⚠ mozjpeg pre-build test failed
npm ERR!   ℹ compiling from source
npm ERR!   ✖ Error: Command failed: /bin/sh -c make -j8
npm ERR! clang: error: no such file or directory: '/usr/local/lib/libpng16.a'
npm ERR! make[2]: *** [cjpeg] Error 1
npm ERR! make[2]: *** Waiting for unfinished jobs....
npm ERR! make[1]: *** [all-recursive] Error 1
npm ERR! make: *** [all] Error 2
npm ERR! 
npm ERR! /Library/Developer/CommandLineTools/usr/bin/make  all-recursive
npm ERR! Making all in java
npm ERR! echo timestamp > classnoinst.stamp
npm ERR! Making all in simd
npm ERR!   GEN      jsimdcfg.inc
npm ERR! /Library/Developer/CommandLineTools/usr/bin/make  all-am
npm ERR!   CPPAS    jsimd_arm64_neon.lo
npm ERR!   CC       libsimd_la-jsimd_arm64.lo
npm ERR!   CCLD     libsimd.la
npm ERR! Making all in md5
npm ERR!   CC       md5cmp-md5cmp.o
npm ERR!   CC       md5cmp-md5.o
npm ERR!   CC       md5cmp-md5hl.o
npm ERR!   CCLD     md5cmp
npm ERR!   CC       cjpeg-cdjpeg.o
npm ERR!   CC       cjpeg-cjpeg.o
npm ERR!   CC       cjpeg-rdgif.o
npm ERR!   CC       cjpeg-rdppm.o
npm ERR!   CC       cjpeg-rdtarga.o
npm ERR!   CC       cjpeg-rdbmp.o
npm ERR!   CC       cjpeg-rdswitch.o
npm ERR!   CC       cjpeg-rdjpeg.o
npm ERR!   CC       cjpeg-rdpng.o
npm ERR!   CC       jcapimin.lo
npm ERR!   CC       jcapistd.lo
npm ERR!   CC       jccoefct.lo
npm ERR!   CC       jccolor.lo
npm ERR!   CC       jcext.lo
npm ERR!   CC       jcdctmgr.lo
npm ERR!   CC       jchuff.lo
npm ERR!   CC       jcinit.lo
npm ERR!   CC       jcmainct.lo
npm ERR!   CC       jcmarker.lo
npm ERR!   CC       jcmaster.lo
npm ERR!   CC       jcomapi.lo
npm ERR!   CC       jcparam.lo
npm ERR!   CC       jcphuff.lo
npm ERR!   CC       jcprepct.lo
npm ERR!   CC       jcsample.lo
npm ERR!   CC       jctrans.lo
npm ERR!   CC       jdapimin.lo
npm ERR!   CC       jdapistd.lo
npm ERR!   CC       jdatadst.lo
npm ERR!   CC       jdatasrc.lo
npm ERR!   CC       jdcoefct.lo
npm ERR!   CC       jdcolor.lo
npm ERR!   CC       jddctmgr.lo
npm ERR!   CC       jdhuff.lo
npm ERR!   CC       jdinput.lo
npm ERR!   CC       jdmainct.lo
npm ERR!   CC       jdmarker.lo
npm ERR!   CC       jdmaster.lo
npm ERR!   CC       jdmerge.lo
npm ERR!   CC       jdphuff.lo
npm ERR!   CC       jdpostct.lo
npm ERR!   CC       jdsample.lo
npm ERR!   CC       jdtrans.lo
npm ERR!   CC       jerror.lo
npm ERR!   CC       jfdctflt.lo
npm ERR!   CC       jfdctfst.lo
npm ERR!   CC       jfdctint.lo
npm ERR!   CC       jidctflt.lo
npm ERR!   CC       jidctfst.lo
npm ERR!   CC       jidctint.lo
npm ERR!   CC       jidctred.lo
npm ERR!   CC       jquant1.lo
npm ERR!   CC       jquant2.lo
npm ERR!   CC       jutils.lo
npm ERR!   CC       jmemmgr.lo
npm ERR!   CC       jmemnobs.lo
npm ERR!   CC       jaricom.lo
npm ERR!   CC       jcarith.lo
npm ERR!   CC       jdarith.lo
npm ERR!   CC       djpeg-cdjpeg.o
npm ERR!   CC       djpeg-djpeg.o
npm ERR!   CC       djpeg-rdcolmap.o
npm ERR!   CC       djpeg-rdswitch.o
npm ERR!   CC       djpeg-wrgif.o
npm ERR!   CC       djpeg-wrppm.o
npm ERR!   CC       djpeg-wrbmp.o
npm ERR!   CC       djpeg-wrtarga.o
npm ERR!   CC       jpegtran.o
npm ERR!   CC       rdswitch.o
npm ERR!   CC       cdjpeg.o
npm ERR!   CC       transupp.o
npm ERR!   CC       rdjpgcom.o
npm ERR!   CC       wrjpgcom.o
npm ERR!   CC       tjbench-tjbench.o
npm ERR!   CC       tjbench-bmp.o
npm ERR!   CC       tjbench-tjutil.o
npm ERR!   CC       tjbench-rdbmp.o
npm ERR!   CC       tjbench-rdppm.o
npm ERR!   CC       tjbench-wrbmp.o
npm ERR!   CC       tjbench-wrppm.o
npm ERR!   CC       libturbojpeg_la-jcapimin.lo
npm ERR!   CC       libturbojpeg_la-jcapistd.lo
npm ERR!   CC       libturbojpeg_la-jccoefct.lo
npm ERR!   CC       libturbojpeg_la-jccolor.lo
npm ERR!   CC       libturbojpeg_la-jcdctmgr.lo
npm ERR!   CC       libturbojpeg_la-jcext.lo
npm ERR!   CC       libturbojpeg_la-jchuff.lo
npm ERR!   CC       libturbojpeg_la-jcinit.lo
npm ERR!   CC       libturbojpeg_la-jcmainct.lo
npm ERR!   CC       libturbojpeg_la-jcmarker.lo
npm ERR!   CC       libturbojpeg_la-jcmaster.lo
npm ERR!   CC       libturbojpeg_la-jcomapi.lo
npm ERR!   CC       libturbojpeg_la-jcparam.lo
npm ERR!   CC       libturbojpeg_la-jcphuff.lo
npm ERR!   CC       libturbojpeg_la-jcprepct.lo
npm ERR!   CC       libturbojpeg_la-jcsample.lo
npm ERR!   CC       libturbojpeg_la-jctrans.lo
npm ERR!   CC       libturbojpeg_la-jdapimin.lo
npm ERR!   CC       libturbojpeg_la-jdapistd.lo
npm ERR!   CC       libturbojpeg_la-jdatadst.lo
npm ERR!   CC       libturbojpeg_la-jdatasrc.lo
npm ERR!   CC       libturbojpeg_la-jdcoefct.lo
npm ERR!   CC       libturbojpeg_la-jdcolor.lo
npm ERR!   CC       libturbojpeg_la-jddctmgr.lo
npm ERR!   CC       libturbojpeg_la-jdhuff.lo
npm ERR!   CC       libturbojpeg_la-jdinput.lo
npm ERR!   CC       libturbojpeg_la-jdmainct.lo
npm ERR!   CC       libturbojpeg_la-jdmarker.lo
npm ERR!   CC       libturbojpeg_la-jdmaster.lo
npm ERR!   CC       libturbojpeg_la-jdmerge.lo
npm ERR!   CC       libturbojpeg_la-jdphuff.lo
npm ERR!   CC       libturbojpeg_la-jdpostct.lo
npm ERR!   CC       libturbojpeg_la-jdsample.lo
npm ERR!   CC       libturbojpeg_la-jdtrans.lo
npm ERR!   CC       libturbojpeg_la-jerror.lo
npm ERR!   CC       libturbojpeg_la-jfdctflt.lo
npm ERR!   CC       libturbojpeg_la-jfdctfst.lo
npm ERR!   CC       libturbojpeg_la-jfdctint.lo
npm ERR!   CC       libturbojpeg_la-jidctflt.lo
npm ERR!   CC       libturbojpeg_la-jidctfst.lo
npm ERR!   CC       libturbojpeg_la-jidctint.lo
npm ERR!   CC       libturbojpeg_la-jidctred.lo
npm ERR!   CC       libturbojpeg_la-jquant1.lo
npm ERR!   CC       libturbojpeg_la-jquant2.lo
npm ERR!   CC       libturbojpeg_la-jutils.lo
npm ERR!   CC       libturbojpeg_la-jmemmgr.lo
npm ERR!   CC       libturbojpeg_la-jmemnobs.lo
npm ERR!   CC       libturbojpeg_la-jaricom.lo
npm ERR!   CC       libturbojpeg_la-jcarith.lo
npm ERR!   CC       libturbojpeg_la-jdarith.lo
npm ERR!   CC       libturbojpeg_la-turbojpeg.lo
npm ERR!   CC       libturbojpeg_la-transupp.lo
npm ERR!   CC       libturbojpeg_la-jdatadst-tj.lo
npm ERR!   CC       libturbojpeg_la-jdatasrc-tj.lo
npm ERR!   CC       jcstest.o
npm ERR!   CC       jpegyuv.o
npm ERR!   CC       yuvjpeg.o
npm ERR!   CC       tjunittest.o
npm ERR!   CC       tjutil.o
npm ERR!   CCLD     libjpeg.la
npm ERR!   CCLD     cjpeg
npm ERR!   CCLD     djpeg
npm ERR!   CCLD     jpegtran
npm ERR!   CCLD     rdjpgcom
npm ERR!   CCLD     wrjpgcom
npm ERR!   CCLD     jpegyuv
npm ERR!   CCLD     jcstest
npm ERR!   CCLD     yuvjpeg
`

**Comment by NikoManiac** [comment]
> Can you try
> 
> ```
> brew update
> brew install libtool
> ```
> 
> One of user has [suggested](https://github.com/imagemin/imagemin/issues/168#issuecomment-314313374) this
> 
> ```
> brew install automake autoconf libtool dpkg pkgconfig nasm libpng
> ```

Thx! This is help me!
