### ISSUE TITLE
js + custom js path + mix.extract and mix.version - missing manifest.js

### ISSUE THREAD

**Issue by FDiskas** [JeffreyWay/laravel-mix#224]
```
"name": "laravel-mix",
"version": "0.5.16"
```

Missing **manifest.js** and **vendros.js** files. But if they exists they must not be cash busted.
To reproduce this bug:
Add one more mix.js after .extract()
Probably extract should work only on files there was compiled before the extract() function.
If I put mix.extract() after all js files - the last directory was used `public/modules/admin/js`. It should be always in the same public js root folder.

**webpack.mix.js**
```js
mix
  .js('resources/assets/js/app.js', 'public/js')
  .extract(['jquery', 'vue', 'lodash'])
  .js('Modules/Admin/Resources/assets/js/admin.js', 'public/modules/admin/js')
  .sass('resources/assets/sass/app.scss', 'public/css')
  .sourceMaps()
  .version()
;
```
generated **mix-manifest.json**
```json
{
  "/js/app.js": "/js/app.62acfad02dae0ca7b6ac.js",
  "/css/app.css": "/css/app.105d2683ae1da59635b4.css",
  "/js/app.js.map": "/js/app.62acfad02dae0ca7b6ac.js.map",
  "/css/app.css.map": "/css/app.105d2683ae1da59635b4.css.map",
  "/modules/admin/js/admin.js": "/modules/admin/js/admin.65d9a742dd40e6c92d09.js",
  "/modules/admin/js/admin.js.map": "/modules/admin/js/admin.65d9a742dd40e6c92d09.js.map"
}
```

**Comment by JeffreyWay** [comment]
@FDiskas Good catch. Yeah, I always assumed that folks would call `mix.extract()` *after* all `mix.js()` references. I've fixed that just now.

One important note, though, is that the `vendor.js` and `manifest.js` files will be placed in the base directory of the last `mix.js()` call. So if you want them to be in the `public/js/`folder, do this:

```js
mix
  .js('Modules/Admin/Resources/assets/js/admin.js', 'public/modules/admin/js')
  .js('resources/assets/js/app.js', 'public/js')
  .extract(['jquery', 'vue', 'lodash'])
  .sass('resources/assets/sass/app.scss', 'public/css')
  .sourceMaps()
  .version()
;
```

**Comment by FDiskas** [comment]
Thanks for the fix

**Comment by ardasatata** [comment]
I can confirm this issue still persist in version 6 
```json
"laravel-mix": "^6.0.49"
```

I created a placeholder file that points 'public/js/' as its output instead to solve this issue
here's my `webpack.mix.js`
```javascript
mix.ts('resources/assets/js/_placeholder_.tsx', 'public/js/_placeholder_.js').react();
mix.extract();
```
hence you can find vendor.js & manifest.js files in the `/public/js/' directory
