### ISSUE TITLE
Mix 5.0.5: Causing UnhandledPromiseRejectionWarning error

### ISSUE THREAD

**Issue by blackdrago** [JeffreyWay/laravel-mix#2465]
-   Laravel Mix Version: 5.0.5 (`npm list --depth=0`)
-   Node Version (`node -v`): v12.12.0
-   NPM Version (`npm -v`): 6.11.3
-   OS: MacOS

### Description:
Running `npm run dev` no longer works once Laravel mix is upgraded to 5.0.5. It's throwing an UnhandledPromiseRejectionWarning about file/directory not existing, but the files in question exist. This error prevents mix from, well, mixing.

The issue is that these files exist. And if I roll back to Mix 5.0.4, everything works swimmingly.

Full error output:
```
(node:26595) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/usr/local/var/www/exedra/resources/assets/js/*.js'
(node:26595) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```

### Steps To Reproduce:
package.json file:
```javavascript
{
    "private": true,
    "scripts": {
        "dev": "npm run development",
        "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "watch": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "watch-poll": "npm run watch -- --watch-poll",
        "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
        "prod": "npm run production",
        "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
    },
    "devDependencies": {
        "cross-env": "^7.0.2",
        "laravel-mix": "^5.0.5",
        "resolve-url-loader": "^3.1.1",
        "sass": "^1.26.10",
        "sass-loader": "^7.1.0"
    }
}
```
webpack.mix.js file:
```javascript
let mix = require('laravel-mix');

mix.disableNotifications();
 
// establish known paths for sanity
let vendorPath     = 'node_modules/',
    assetPath      = 'resources/assets/',
    libPath        = assetPath + 'lib/',
    sassPath       = assetPath + 'sass/',
    sassVarPath    = sassPath + 'variables/',
    cssPath        = assetPath + 'css/',
    jsPath         = assetPath + 'js/',
    cvmPath        = 'modules/CompositeViews/',
    cvmAssetPath   = cvmPath + 'Resources/assets/',
    cvmSassPath    = cvmAssetPath + 'sass/',
    cvmSassVarPath = cvmSassPath + 'variables/',
    bvmPath        = 'modules/BinViews/',
    bvmAssetPath   = bvmPath + 'Resources/assets/',
    bvmSassPath    = bvmAssetPath + 'sass/',
    bvmSassVarPath = bvmSassPath + 'variables/';
 
// compile all SASS styles from modules and primary resources
mix.sass(bvmSassPath + 'module.scss', 'assets/css/compiled-bvm.css').setPublicPath('resources');
mix.sass(cvmSassPath + 'module.scss', 'assets/css/compiled-cvm.css').setPublicPath('resources');
mix.sass(sassPath + 'app.scss', 'assets/css/compiled-sass.css').setPublicPath('resources');

// combine javascript files
mix.scripts([
    assetPath + 'descriptor.js',
    jsPath + '*.js'
], 'public/js/app.js');

// combine app styles into one CSS file
mix.styles([
    cssPath + '*.css',
], 'public/css/app.css');
```

With Laravel Mix 5.0.5 installed, run the following command:
`npm run dev`

Downgrade to Laravel Mix 5.0.4 and run the same command and no error appears. The mix completes without issue.

**Comment by RobertoGongora** [comment]
I'm getting the same issue. I can probably share logs if needed.

**Comment by fatihgune** [comment]
Instead of using an asterisk for all files under specified folder (`*.js`, `*.css` etc), use the full file path. 

For example:

`mix.scripts([
    'resources/js/utility/add_me_to_scripts.js',
    'resources/js/filters/you_dont_wanna_forget_me.js'
], 'public/js/app.js');`

**Comment by blackdrago** [comment]
I appreciate the workaround as an option, but, as far as I know, the wildcard is a valid option from Laravel Mix for both CSS and JS files. Unless that's slated to change? (I hope not.)

Using the full file path of every single file isn't a great solution when you have many, many files... not to mention that you'd have to update the mix file every time you add/remove a file.

**Comment by emericklaw** [comment]
I am also experiencing this issue.

`(node:5334) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/application/resources/assets/js/pages/*.js'`


Been using this for ages:
`mix.scripts('resources/assets/js/pages/*.js', 'public/js/pages.js');`

Now have to list each separatly:
```
mix.scripts([
    'resources/assets/js/pages/_global.js',
...
    'resources/assets/js/pages/guide.js'
    ]
    , 'public/js/pages.js');
```

**Comment by reidkornman** [comment]
I am having the same issue as described above by OP, and the workaround is a bit of a maintenance nightmare.

**Comment by P-iknow** [comment]
i am having the same issue as described above, 
![image](https://user-images.githubusercontent.com/35516239/93070072-627d8f80-f6b9-11ea-9478-78e7cf5eefa6.png)

**Comment by P-iknow** [comment]
I resolved this issue by changing the version from 5.0.5 to 5.0.4.
![image](https://user-images.githubusercontent.com/35516239/93071883-ac677500-f6bb-11ea-8c92-f415a9373bc9.png)

**Comment by neoteknic** [comment]
same issue here, any temp fix ? maybe previous version ?

**Comment by P-iknow** [comment]
@neoteknic 
in the previous version, issue was resolved.

**Comment by neoteknic** [comment]
Ok simple temp fix :  
"laravel-mix": "5.0.4", in package json and npm install

**Comment by tsharms** [comment]
Got the same issue on the following code running laravel-mix@5.0.5, reverting to 5.0.4 fixes the warning.

```
{
			apply: (compiler) => {
                compiler.hooks.done.tap('SpritemapFileRemover', (compilation) => {
                    // After the compiler is done remove the spritemap.js file created by SVGSpritemapPlugin.
                    // This workaround is needed due to the versioning plugin requiring all created files to be present
                    //  for versioning.
                    const fs = require('fs');
                    const spritemapPath = mix.config.publicPath + '/spritemap.js';
                    if (fs.existsSync(spritemapPath)) {
                        fs.unlinkSync(spritemapPath);
                    }
                });
            },
		}
```

**Comment by neoteknic** [comment]
any 5.0.6 to fix ?

**Comment by JeffreyWay** [comment]
Can someone give me a basic example to reproduce this?

**Comment by reidkornman** [comment]
Something as simple as this seems to break on my solution under ("webpack.mix.js")

mix.scripts([
    'resources/js/vendor/*.js',
    'resources/js/security/*.js'
], 'public/js/security.js');

**Comment by JeffreyWay** [comment]
Thank you. Fixed.

**Comment by reidkornman** [comment]
Just curious because I'm new to this ... will this end up in a 5.0.6 release or what's the process? Thank you.

**Comment by jafarchoupan** [comment]
`(node:92562) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'resources/assets/css/vendor/*.css'`
same package.json file with webpack-mix version 5.0.5 have this error and not render my files . 
please help me solve this problem  .

**Comment by tsharms** [comment]
@jafarchoupan updating to version 5.0.6 or 5.0.7 should fix this issue.

**Comment by jafarchoupan** [comment]
> @jafarchoupan updating to version 5.0.7 should fix this issue.
steps : 
rm -rf node_modules 
rm package-lock.json 
npm cache clean --force 
Both version check 5.0.6 and 5.0.7 , I still have the problem .

**Comment by tsharms** [comment]
Hmm I'm sorry, I saw that the version was bumped to 5.0.7 and was expecting that it features the fix for this problem. The only solution for now is locking Laravel Mix add version 5.0.4 :(

`"laravel-mix": "5.0.4"`

**Comment by jafarchoupan** [comment]
@tsharms 
i used version 5.0.4 by the way and get this Error . 
any body don't know this problem ?

**Comment by reidkornman** [comment]
> @tsharms
> i used version 5.0.4 by the way and get this Error .
> any body don't know this problem ?

This is still pending being merged into a release. @JeffreyWay mentioned it may be back ported once v6 is finalized, hopefully.

**Comment by jafarchoupan** [comment]
@reidkornman 
So should I run until then? which one version must be run my project ?

**Comment by reidkornman** [comment]
> @reidkornman
> So should I run until then? which one version must be run my project ?

I'm running 5.0.4 without an issue currently. That's what I would advise.

**Comment by Adizbek** [comment]
5.0.9, not fixed yet.

**Comment by reidkornman** [comment]
It looks like the focus is on 6.0 being released. Any plans to fix this in the 5.x branch @JeffreyWay ? It looks like 5.0.9 is out but not marked as "latest" (5.0.5 is currently marked as latest). I haven't seen anything on this since Jeff's comment 2 months ago.
