### ISSUE TITLE
mix-entry.js missing on less compile

### ISSUE THREAD

**Issue by faustbrian** [JeffreyWay/laravel-mix#359]
- Laravel Mix Version: 0.7.4
- Node Version (`node -v`):  v7.5.0
- NPM Version (`npm -v`):  4.2.0
- OS: macOS Sierra 10.12.3

### Description:

Everytime I try to compile my less files this error comes up. I tried to compile sass files on another project and there it is working, seems to be an issue with less files.

Setup is fresh and without any changes to the webpack.mix.js besides compiling less instead of sass.

```
 ERROR  Failed to compile with 1 errors

 error  in ./mix-entry.js

Module build failed: Error: ENOENT: no such file or directory, open '/Users/Brian/Sites/project/mix-entry.js'

 @ multi ./mix-entry.js ./resources/assets/less/app.less
```

**Comment by JeffreyWay** [comment]
Please paste in your webpack.mix.js file.

**Comment by faustbrian** [comment]
```
const { mix } = require('laravel-mix');

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel application. By default, we are compiling the Sass
 | file for the application as well as bundling up all the JS files.
 |
 */

mix.js('resources/assets/js/app.js', 'public/js')
   .less('resources/assets/sass/app.less', 'public/css');
```

**Comment by JeffreyWay** [comment]
Are you sure that's your Mix file? The error you're getting doesn't match up with that. 

Also, it's squawking about `./resources/assets/less/app.less`, but the Mix file you pasted has `'resources/assets/sass/app.less`

**Comment by faustbrian** [comment]
Yeah I renamed the folder to less but this is my mix file.

**Comment by JeffreyWay** [comment]
The thing is that `mix-entry.js` will only ever be created if you don't call `mix.js()`. So I'm not sure how it's possible that you're seeing this error with that Mix file. Hmm..

**Comment by kuroisuna** [comment]
I also had this problem early in the morning:

```
 WAIT  Compiling...

 95% emitting
 ERROR  Failed to compile with 1 errors

 error  in ./mix-entry.js

Module build failed: Error: ENOENT: no such file or directory, open '/Users/axel/Development/misc/cmclux/mix-entry.js'
    at Error (native)

 @ multi ./mix-entry.js ./resources/assets/sass/app.scss

                            Asset       Size  Chunks             Chunk Names
      mix.64788981567b308f9776.js    2.91 kB       0  [emitted]  mix
/css/app.28d59aa165bb4494e01e.css    2.58 kB       0  [emitted]  mix
                mix-manifest.json  100 bytes          [emitted]
```

My mix file at that moment:

```js
mix
	// .js('resources/assets/js/app.js', 'public/js')
   .sass('resources/assets/sass/app.scss', 'public/css')
   .version();
```

I solved it uncommenting the js method.

**Comment by kuroisuna** [comment]
I also had this problem early in the morning in macOS Sierra:

``` WAIT  Compiling...

 95% emitting
 ERROR  Failed to compile with 1 errors

 error  in ./mix-entry.js

Module build failed: Error: ENOENT: no such file or directory, open '/Users/axel/Development/misc/cmclux/mix-entry.js'
    at Error (native)

 @ multi ./mix-entry.js ./resources/assets/sass/app.scss

                            Asset       Size  Chunks             Chunk Names
/css/app.20e4509b0f7a5f2a62ff.css    2.58 kB       0  [emitted]  mix
                mix-manifest.json  100 bytes          [emitted]
```

My mix file at that moment:

```js
mix
   // .js('resources/assets/js/app.js', 'public/js')
   .sass('resources/assets/sass/app.scss', 'public/css')
   .version();
```

I fixed it uncommenting the `.js`method.

**Comment by dnlcorrea** [comment]
Same here, @kuroisuna.

I opted for not using webpack for JS, since I still can't figure out how to require materialize-css in that project. But I'm using less. I ended up creating an empty js file for the time being.

**Comment by Turbotailz** [comment]
Also getting this issue, all I'm using is SASS:

`const { mix } = require('laravel-mix');

mix.sass('resources/assets/sass/app.scss', 'public/css');`

Getting this error:

`ERROR  Failed to compile with 1 errors

 error  in ./mix-entry.js

Module build failed: Error: ENOENT: no such file or directory, open 'E:\Laravel\helpr\mix-entry.js' at Error (native)

            Asset       Size  Chunks             Chunk Names
           mix.js     2.9 kB       0  [emitted]  mix
     /css/app.css  823 bytes       0  [emitted]  mix
mix-manifest.json   58 bytes          [emitted]`

**Comment by Turbotailz** [comment]
Also getting this issue, all I'm using is SASS:

```javascript
const { mix } = require('laravel-mix');

mix.sass('resources/assets/sass/app.scss', 'public/css');
```

Getting this error:

```
ERROR  Failed to compile with 1 errors

error  in ./mix-entry.js

Module build failed: Error: ENOENT: no such file or directory, open 'E:\Laravel\helpr\mix-entry.js' at Error (native)

            Asset       Size  Chunks             Chunk Names
           mix.js     2.9 kB       0  [emitted]  mix
     /css/app.css  823 bytes       0  [emitted]  mix
mix-manifest.json   58 bytes          [emitted]
```

**Comment by JeffreyWay** [comment]
This is fixed in #366.
