### ISSUE TITLE
HMR not Working when using Copy Plugin

### ISSUE THREAD

**Issue by SeoFood** [JeffreyWay/laravel-mix#63]
npm run hmr
```javascript
mix.js('resources/assets/js/app.js', 'public/js')
mix.copy('node_modules/bootstrap/fonts', 'public/fonts')
```

This error preventing hot reload from working:
```
ERROR in [copy-webpack-plugin] Using older versions of webpack-dev-server, devServer.outputPath must be defined to write to absolute paths
```

npm run hmr
```javascript
mix.js('resources/assets/js/app.js', 'public/js')
//mix.copy('node_modules/bootstrap/fonts', 'public/fonts')
```

Works.

I tried to use the output path as an absolute path but it can't find any js file.

**Comment by QWp6t** [comment]
Try:
```sh
yarn add webpack-dev-server@2.2.0-rc.0 --dev
# npm i webpack-dev-server@2.2.0-rc.0 -D
```

**Comment by SeoFood** [comment]
yeah tried this already. It is related to the copy-webpack-plugin

https://github.com/kevlened/copy-webpack-plugin/issues/29

**Comment by jbreuer95** [comment]
@SeoFood Any workaround? Downgrading copy-webpack didnt work for me

**Comment by SeoFood** [comment]
@jbreuer95 no not yet sorry, spend an hour to find the problem. The copy plugin doesn't seem to be really stable. Dunno if there are better webpack copy plugins who support the webpack dev server.

**Comment by nmfzone** [comment]
So, until this fixed, we can't use `hmr`? Because I have `.copy()` in my `webpack.mix`. Sad :/

**Comment by SeoFood** [comment]
Yes didn't find a fix for that yet.

**Comment by jbreuer95** [comment]
@SeoFood thanks for trying :)

**Comment by solicomo** [comment]
It seems to have been fixed on master. #150 

waiting for new release...

**Comment by jbreuer95** [comment]
@solicomo 
it still doesn't work for me, for now i remove the mix copy's when i run hmr and user ../ paths instead of / paths.

**Comment by rmartins90** [comment]
Any solution for this?

**Comment by jbruni** [comment]
My temporary solution is to wrap the `mix.copy` entries in a condition, as follows:

```
if (mix.config.inProduction) {
    mix.copy('node_modules/bootstrap/fonts', 'public/fonts');
}
```

Of course, to have the assets copied, I need to use `npm run production` once.

**Comment by JeffreyWay** [comment]
This is fixed in the next tagged release.

**Comment by nmfzone** [comment]
Awesome!
