### ISSUE TITLE
Laravel Mix doesn't seem to transpile ES6 when importing packages

### ISSUE THREAD

**Issue by lucidlemon** [JeffreyWay/laravel-mix#971]
- Laravel Mix Version: 1.0.7 
- Node Version: 8.1.3
- NPM Version: 5.1.0
- OS: macOS 10.12.6 Beta

### Description:

Laravel Mix doesn't seem to transpile ES6 when importing packages

### Steps To Reproduce:

Installed laravel mix according to [documentation for a standalone project](https://github.com/JeffreyWay/laravel-mix/blob/master/docs/installation.md).

created the standard directory structure (`src/app.js`, `src/app.scss`, created a folder `dist`) and added a [custom file](https://gist.github.com/lucidlemon/7d9d7d1dfb1d9811796db0aa78f76173) as myPackage.js.

`src/app.js` now contains the following:

```
import { initTabSwitcher } from './myPackage.js';

initTabSwitcher('.tabs a');
```

Running `npm run dev` and `npm run production` works fine now.

## To the Problem

If i put `myPackage.js` into my own git repository (as I want to share the functions across projects), install it via npm (`"myPackage": "git+ssh://git@myServer.com:myUser/myPackage.git"`) and import it this way:

```
import { initTabSwitcher } from 'myPackage';

initTabSwitcher('.tabs a');
```

I get this error upon running `npm run production`:

`Unexpected token: name (matchesFn) [./~/myPackage/src/app.js:3,0][/app.js:97,6]`

`npm run dev` runs absolutely fine, but does not minify anything.

I also tried installing uglifyJS by adding `"uglify-js": "git+https://github.com/mishoo/UglifyJS2.git#harmony"` into my devDependencies. It didn't change anything.

Is Laravel Mix not applying transpilation to imported modules? Am I doing something wrong or is this a bug?

**Comment by Juje** [comment]
I can confirm this problem.

When I imported the Bootstrap dropdown module everything worked perfectly when using `npm run dev` but when I tried running `npm run prod` I got the following error:
```
js/app.js from UglifyJs
Unexpected token: operator (>) [./~/bootstrap/js/src/dropdown.js:11,0][js/app.js:20252,23]
```
And on that line the following JS can be seen:
```
const Dropdown = (($) => {
```
So I can confirm that ES6 is giving some issues with the Uglify system.

**Comment by domstubbs** [comment]
The default Babel rules [exclude](https://github.com/JeffreyWay/laravel-mix/blob/643f9b90059e8543750c3ee0703c3d2921e5f719/src/builder/webpack-rules.js#L11) the node_modules directory.

I’ve posted a sample config override [here](https://github.com/JeffreyWay/laravel-mix/issues/949#issuecomment-314406812) which has sorted this for me. I’m still excluding node_modules in general, the only exception is the foundation-sites package, which currently requires transpiling.

**Comment by Juje** [comment]
@domstubbs Sadly the code you posted in that link doesn't work for me :( .
But there is an [Uglify-ES](https://www.npmjs.com/package/uglify-es) edition and this seems to work perfectly if you include the beta version of [WebPack-UglifyJS-Plugin](https://github.com/webpack-contrib/uglifyjs-webpack-plugin).
So I guess we just have to wait till [WebPack-UglifyJS-Plugin](https://github.com/webpack-contrib/uglifyjs-webpack-plugin) releases the stable version so LaravelMix will have it too.
But I'm happy that the solution you posted works for some.

**Comment by domstubbs** [comment]
@Juje I assumed that you were running into the same node_modules exclusion issue that I was, since I’d been getting the same errors from UglifyJS, but looking at the path in your error message I think I might’ve jumped the gun there.

If you have code that isn’t being transpiled even though it isn’t in a node_modules or bower_components directory I’m not sure what the cause for that could be. Not that that’s saying much as I’m still trying to figure Webpack out myself.

**Comment by JeffreyWay** [comment]
Yes, this is 100% because we exclude the node_modules directory. It speeds things up a good bit, as I understand. 

But - the question does pop up somewhat frequently, so we need to decide if we should remove that exclusion entirely. Or, I could make it an opt-in config option.

**Comment by devcircus** [comment]
Opt-in sounds like a win-win.

**Comment by thecrypticace** [comment]
Agreed. I've got a situation where enabling `mix.sourceMaps()` breaks some dependencies code in Safari (in a non-production build only — though uglify can't handle the ES6 so production builds break for a diff reason). Transpiling that code makes the problem disappear completely.

The alternative fix for me (that I've done for now) is used webpack's alias support import the precompiled version instead. This was definitely a weird problem to track down.

Would it be worth making the opt-in also capable of specifying an array? (So I could say I want dependencies X, Y, and Z to be transpiled)

**Comment by JeffreyWay** [comment]
I think the uglify webpack plugin is really close to being tagged, and that should fix this issue. So I'll tag a new Mix release as soon as they make it official.

**Comment by OwenMelbz** [comment]
@JeffreyWay is there any movement on this? been a month now and the issue seems still present :(

```
/js/app.js from UglifyJs
Unexpected token: name (googleCharts) [./node_modules/google-charts/googleCharts.js:3,0][/js/app.js:58074,6]
```

**Comment by OwenMelbz** [comment]
For anybody else who wants a work around as @domstubbs said you can change the exclusions

Currently this is a fully working `webpack.mix.js` example that may be useful for people

```js
const { mix } = require('laravel-mix');

mix.js('resources/assets/js/app.js', 'public/js')
   .sass('resources/assets/sass/app.scss', 'public/css');

if (mix.inProduction()) {

    mix.version();

    mix.webpackConfig({
        module: {
            rules: [{
                test: /\.js?$/,
                exclude: /(bower_components)/,
                use: [{
                    loader: 'babel-loader',
                    options: mix.config.babel()
                }]
            }]
        }
    });
}


```

**Comment by Daedalus11069** [comment]
@OwenMelbz As far as I can tell, the [uglify-webpack-plugin](https://github.com/webpack-contrib/uglifyjs-webpack-plugin/releases) still hasn't released an updated version, which is when it would be said there'd be movement on this.

**Comment by rjvim** [comment]
Any update on this problem apart from workaround from @OwenMelbz ?

**Comment by robbyrice** [comment]
The latest version of Laravel Mix (1.6.0) resolves this problem.

**Comment by jdriesen** [comment]
@robbyrice  ....
If I can ask... what exactly has to be done to solve the problem ?
I ran into the same problem, though I'm NOT using Laravel at all...

Thanks in advance for your reply,
Johnny

**Comment by robbyrice** [comment]
@jdriesen you shouldn't have to do anything special.  The latest version of Laravel Mix has switched to a version of uglifyjs that supports minifying es2015 code.  Let me know if you are running into a specific problem and I'll see if I can help.
