### ISSUE TITLE
Dependencies not found error references my own files

### ISSUE THREAD

**Issue by Hendriksie** [JeffreyWay/laravel-mix#983]
- Laravel Mix Version: `+-- laravel-mix@1.1.1`
- Node Version: `v8.1.3`
- NPM Version: `5.2.0`
- OS: `Windows 10`

`npm list --depth=0` does give me an error though (even when manually installing webpack):
```
`-- webpack@2.2.0

npm ERR! peer dep missing: webpack@^2.2.0, required by extract-text-webpack-plugin@2.1.2
```

Complete list:

```
+-- axios@0.15.3
+-- bootstrap-sass@3.3.7
+-- cropperjs@1.0.0-rc.3
+-- cross-env@5.0.1
+-- flatpickr@2.6.3
+-- jquery@3.2.1
+-- jquery-mousewheel@3.1.13
+-- laravel-mix@1.1.1
+-- lodash@4.17.4
+-- malihu-custom-scrollbar-plugin@3.1.5
+-- nouislider@9.2.0
+-- owl.carousel@2.2.0
+-- tinymce@4.6.4
+-- vue@2.3.4
`-- webpack@2.2.0

npm ERR! peer dep missing: webpack@^2.2.0, required by extract-text-webpack-plugin@2.1.2
```

### Description:
Since updating `laravel-mix` and `npm` I receive the following error:

```
These dependencies were not found:

* C:\Projects\project-name\resources\assets\js\cms\cms.js in multi ./resources/assets/js/cms/cms.js ./resources/assets/sass/cms/cms.scss ./resources/assets/sass/website/style.scss
* C:\Projects\project-name\resources\assets\js\website\website.js in multi ./resources/assets/js/website/website.js
* C:\Projects\project-name\resources\assets\sass\cms\cms.scss in multi ./resources/assets/js/cms/cms.js ./resources/assets/sass/cms/cms.scss ./resources/assets/sass/website/style.scss
* C:\Projects\project-name\resources\assets\sass\website\style.scss in multi ./resources/assets/js/cms/cms.js ./resources/assets/sass/cms/cms.scss ./resources/assets/sass/website/style.scss

To install them, you can run: npm install --save C:\Projects\project-name\resources\assets\js\cms\cms.js C:\Projects\project-name\resources\assets\js\website\website.js C:\Projects\project-name\resources\assets\sass\cms\cms.scss C:\Projects\project-name\resources\assets\sass\website\style.scss
```

So I tried reverting the update back but the error does not go away.
When I empty to files to `//` the error still occurs.
Only when removing the `mix` entries the error goes away.

My `webpack.mix.js` file:

```
const {mix} = require('laravel-mix');

mix.disableNotifications();

mix.options({
    processCssUrls: false
});

mix.js('resources/assets/js/cms/cms.js', 'public/build/js/cms.js')
    .js('resources/assets/js/website/website.js', 'public/build/js/website.js')
    .sass('resources/assets/sass/cms/cms.scss', 'public/build/css/cms.css')
    .sass('resources/assets/sass/website/style.scss', 'public/build/css/website.css');

if (mix.inProduction()) {
    mix.version();
}
```

The following scripts gives me that error:

```
npm run dev
```
```
npm run prod
```
```
npm run watch
```

My package.json:

```
{
	"private": true,
	"scripts": {
		"dev": "npm run development",
		"development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
		"watch": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
		"watch-poll": "npm run watch -- --watch-poll",
		"hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
		"prod": "npm run production",
		"production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
	},
	"devDependencies": {
		"cross-env": "^5.0.1",
		"laravel-mix": "^1.1.1",
		"webpack": "2.2.0"
	},
	"dependencies": {
		"axios": "^0.15.2",
		"bootstrap-sass": "^3.3.7",
		"cropperjs": "^1.0.0-beta.2",
		"flatpickr": "^2.3.7",
		"jquery": "^3.1.0",
		"jquery-mousewheel": "^3.1.13",
		"lodash": "^4.16.2",
		"malihu-custom-scrollbar-plugin": "^3.1.5",
		"nouislider": "^9.2.0",
		"owl.carousel": "^2.2.0",
		"tinymce": "^4.6.4",
		"vue": "^2.0.1"
	},
	"eslintConfig": {
		"extends": "eslint:recommended",
		"parserOptions": {
			"ecmaVersion": 6,
			"sourceType": "module"
		},
		"env": {
			"browser": true,
			"node": true
		},
		"globals": {
			"_": true,
			"axios": true
		}
	}
}
```

**Comment by Hendriksie** [comment]
Tested with a fresh installation of Laravel, but get the same error

**Comment by canthis** [comment]
Same problem here since upgrade to laravel-mix@1.1.1
OS - Linux Mint 18.1

**Comment by Hendriksie** [comment]
I think a dependency of `laravel-mix` could be the issue,  this morning a pipeline of my project passed while using `npm 5.2.0` but not the latest version of `laravel-mix`.

**Comment by JeffreyWay** [comment]
I just did a fresh install of Laravel and Mix, and everything compiled properly. Hmm..

**Comment by Hendriksie** [comment]
Tested again with a fresh installation of `laravel` but still not working.

Complete NPM log here:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Wesley Hendriks\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@5.2.0
3 info using node@v8.1.3
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle @~predev: @
6 info lifecycle @~dev: @
7 verbose lifecycle @~dev: unsafe-perm in lifecycle true
8 verbose lifecycle @~dev: PATH: C:\Users\Wesley Hendriks\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Projects\test-laravel\node_modules\.bin;C:\Users\Wesley Hendriks\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\cmd;C:\Program Files\ConEmu\ConEmu\Scripts;C:\Program Files\ConEmu;C:\Program Files\ConEmu\ConEmu;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\WinSCP;C:\Program Files\Git\cmd;C:\php;C:\ProgramData\ComposerSetup\bin;C:\Users\Wesley Hendriks\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit;C:\Program Files\Microsoft SQL Server\130\Tools\Binn;C:\Program Files\nodejs;C:\Users\Wesley Hendriks\AppData\Roaming\Composer\vendor\bin;C:\Users\Wesley Hendriks\AppData\Local\Microsoft\WindowsApps;C:\Users\Wesley Hendriks\AppData\Roaming\npm;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
9 verbose lifecycle @~dev: CWD: C:\Projects\test-laravel
10 silly lifecycle @~dev: Args: [ '/d /s /c', 'npm run development' ]
11 silly lifecycle @~dev: Returned: code: 2  signal: null
12 info lifecycle @~dev: Failed to exec dev script
13 verbose stack Error: @ dev: `npm run development`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\Wesley Hendriks\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\Wesley Hendriks\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:897:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
14 verbose pkgid @
15 verbose cwd C:\Projects\test-laravel
16 verbose Windows_NT 10.0.15063
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Wesley Hendriks\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
18 verbose node v8.1.3
19 verbose npm  v5.2.0
20 error code ELIFECYCLE
21 error errno 2
22 error @ dev: `npm run development`
22 error Exit status 2
23 error Failed at the @ dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]

```

**Comment by tsndr** [comment]
Same here

**Comment by thijsvdanker** [comment]
I had the same issue using laravel-mix on a non Laravel project.
Running `npm install --save-dev babel-loader babel-core babel-preset-env webpack` fixed the issue for me.

**Comment by khaledelmahdi** [comment]
Same here:
```
npm -v: 5.2.0
node-v: v6.11.0
MacOS 10.12.5
```
when I do `npm list --depth=0` I get this error: `npm ERR! peer dep missing: webpack@^2.2.0, required by extract-text-webpack-plugin@2.1.2`

## Description:
```
laravel new test
cd test
npm i
npm run dev
```
I get this error:

```
> @ dev /Users/khaled/bitbucket/lettingbox/test
> npm run development


> @ development /Users/khaled/bitbucket/lettingbox/test
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

 95% emitting                                                                      

 ERROR  Failed to compile with 2 errors                                                                               2:23:56 PM

These dependencies were not found:

* /Users/khaled/bitbucket/lettingbox/test/resources/assets/js/app.js in multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss
* /Users/khaled/bitbucket/lettingbox/test/resources/assets/sass/app.scss in multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss

To install them, you can run: npm install --save /Users/khaled/bitbucket/lettingbox/test/resources/assets/js/app.js /Users/khaled/bitbucket/lettingbox/test/resources/assets/sass/app.scss
     Asset    Size  Chunks             Chunk Names
/js/app.js  2.8 kB       0  [emitted]  /js/app
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/khaled/.npm/_logs/2017-07-11T13_23_57_154Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/khaled/.npm/_logs/2017-07-11T13_23_57_174Z-debug.log
```

**Comment by khaledelmahdi** [comment]
@thijsvdanker I tried your suggestion and didn't work.

**Comment by canthis** [comment]
@thijsvdanker I've also installed sass-loader and then it worked! Thanks!

**Comment by tsndr** [comment]
So this command should fix it: `npm i --save-dev babel-core babel-loader babel-preset-env sass-loader`

Also my `package.json` for reference:
```JSON
{
  "private": true,
  "scripts": {
    "dev": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch-prod": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch-poll": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --watch-poll --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
    "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
  },
  "devDependencies": {
    "autosize": "^3.0.21",
    "axios": "^0.16.2",
    "babel-core": "^6.25.0",
    "babel-loader": "^7.1.1",
    "babel-preset-env": "^1.6.0",
    "bootstrap": "^4.0.0-alpha.6",
    "cross-env": "^5.0.1",
    "font-awesome": "^4.7.0",
    "jquery": "^3.2.1",
    "laravel-mix": "^1.1.1",
    "lodash": "^4.17.4",
    "multiple-date-picker": "^2.1.2",
    "pikaday": "^1.6.1",
    "sass-loader": "^6.0.6",
    "vue": "^2.3.4",
    "vue-resource": "^1.3.4"
  }
}
```

**Comment by khaledelmahdi** [comment]
I tried `npm i --save-dev babel-core babel-loader babel-preset-env sass-loader` and still didn't work. I think it has something with npm 5.2.0 version.

**Comment by tsndr** [comment]
@khaledelmahdi i've updated my last comment, try it now

**Comment by tsndr** [comment]
@khaledelmahdi If you're using less you probably have to install less-loader either.

**Comment by JeffreyWay** [comment]
I've just pushed Mix 1.2.0, which bumps the extract-text dependency.  Can someone update and let me know if that fixes the issue?

You all shouldn't need to manually install any of those packages you're listing.

**Comment by tsndr** [comment]
@JeffreyWay thank you very much for the update, but something is still not working on a fresh Laravel.

```
macbookpro:laravel_test tobi$ npm run dev

> @ dev /Users/tobi/Sites/php/laravel_test
> npm run development


> @ development /Users/tobi/Sites/php/laravel_test
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

 95% emitting                                                                 p       
 ERROR  Failed to compile with 1 errors                                 15:56:17

This relative module was not found:

* ./components/Example.vue in ./resources/assets/js/app.js
                                                                                                    Asset     Size  Chunks                    Chunk Names
  fonts/vendor/bootstrap-sass/bootstrap/glyphicons-halflings-regular.eot?f4769f9bdb7466be65088239c12046d1  20.1 kB          [emitted]         
fonts/vendor/bootstrap-sass/bootstrap/glyphicons-halflings-regular.woff2?448c34a56d699c29117adc64c43affeb    18 kB          [emitted]         
 fonts/vendor/bootstrap-sass/bootstrap/glyphicons-halflings-regular.woff?fa2772327f55d8198301fdb8bcfc8158  23.4 kB          [emitted]         
  fonts/vendor/bootstrap-sass/bootstrap/glyphicons-halflings-regular.ttf?e18bbf611f2a2e43afc071aa2f4e1512  45.4 kB          [emitted]         
  fonts/vendor/bootstrap-sass/bootstrap/glyphicons-halflings-regular.svg?89889688147bd7575d6327160d64e760   109 kB          [emitted]         
                                                                                               /js/app.js  1.18 MB       0  [emitted]  [big]  /js/app
                                                                                             /css/app.css   147 kB       0  [emitted]         /js/app
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tobi/.npm/_logs/2017-07-11T13_56_17_732Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tobi/.npm/_logs/2017-07-11T13_56_17_756Z-debug.log
```

**Comment by khaledelmahdi** [comment]
@JeffreyWay on a fresh laravel install, still didn't work.
```
> @ dev /Users/khaled/bitbucket/lettingbox/test
> npm run development


> @ development /Users/khaled/bitbucket/lettingbox/test
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

 95% emitting                                                                      

 ERROR  Failed to compile with 2 errors                                                                                                            2:57:37 PM

These dependencies were not found:

* /Users/khaled/bitbucket/lettingbox/test/resources/assets/js/app.js in multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss
* /Users/khaled/bitbucket/lettingbox/test/resources/assets/sass/app.scss in multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss

To install them, you can run: npm install --save /Users/khaled/bitbucket/lettingbox/test/resources/assets/js/app.js /Users/khaled/bitbucket/lettingbox/test/resources/assets/sass/app.scss
     Asset    Size  Chunks             Chunk Names
/js/app.js  2.8 kB       0  [emitted]  /js/app
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/khaled/.npm/_logs/2017-07-11T13_57_37_616Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/khaled/.npm/_logs/2017-07-11T13_57_37_632Z-debug.log
```

**Comment by khaledelmahdi** [comment]
Can it have anything to do with this issue: https://github.com/npm/npm/issues/17717 ?

**Comment by canthis** [comment]
@JeffreyWay For me it worked as expected. Thanks for update!

**Comment by JeffreyWay** [comment]
@khaledelmahdi I just bumped to 5.2 on my Mac, and it still seems to compile properly. Maybe different for Windows users? 

Anyone experiencing this issue want to downgrade npm to 5.0.3 and see if changes anything?

**Comment by tsndr** [comment]
The loaders (babel-loader, sass-loader, vue-loader, ...) are required to work!
If they'd be manually installed it works:
```
npm i --save-dev babel-loader sass-loader vue-loader
```

**Comment by tsndr** [comment]
I am using a Mac with 5.2

**Comment by JeffreyWay** [comment]
@tsndr You're right that they are required to work, but Mix already installs those for you. So it seems like this is an issue related to npm not installing these dependencies properly.

https://github.com/JeffreyWay/laravel-mix/blob/master/package.json#L30-L65

**Comment by khaledelmahdi** [comment]
@JeffreyWay I am using Mac, I downgraded to 5.1, then `rm -rf node_modules && npm cache clean --force && npm install` and now running fine.

I didn't add add any packages manually.

**Comment by JeffreyWay** [comment]
@khaledelmahdi Hmm, interesting. Okay thanks for doing that. Good to know.

**Comment by khaledelmahdi** [comment]
@JeffreyWay How I can see the details of the notification message?

![screen shot 2017-07-11 at 12 43 55](https://user-images.githubusercontent.com/9323496/28073058-983b2778-664c-11e7-8448-12f4fe78c3ae.png)

This what used to appear with npm 5.2.0, but nothing similar to this message on the terminal.

**Comment by tsndr** [comment]
@khaledelmahdi In my notification center the full message was displayed

<img width="326" alt="bildschirmfoto 2017-07-11 um 16 24 30" src="https://user-images.githubusercontent.com/2940127/28073271-89795bb6-6655-11e7-989c-4c14a0407ff9.png">

**Comment by tsndr** [comment]
So the easiest fix is to downgrade to npm@5.1.0 using `npm i -g npm@5.1.0`

**Comment by Hendriksie** [comment]
I have an build that passed this morning using NPM version `5.2.0` So it's weird, only when I updated `laravel-mix` everything went broken.

On the other hand, my colleague still had `laravel-mix` version `^0.6` and it broke for him on NPM version `5.2.0` we use for our pipeline...

**Comment by ruchern** [comment]
Unable to reproduce the error on:

`npm run dev`
`npm run watch`
`npm run prod`

npm: `v5.2.0`
node: `v8.1.3`
laravel-mix: `1.1.1`

**Comment by andrefcbotelho** [comment]
Thanks @tsndr, downgrading NPM worked perfectly for us!

**Comment by ruchern** [comment]
This seems to be an error with npm`5.2.0`, just downgrade back to `5.1.0` and it should work.

**Comment by Hendriksie** [comment]
Downgrading with cache clearing indeed worked for me. Didn't thought about clearing cache the first few times I tried downgrading NPM so that's why it probably didn't work.

Still weird why I have several builds passing using NPM 5.2 though...

**Comment by JonasDoebertin** [comment]
Had the same issue after upgrading to npm@5.2.0.

Downgrading and reinstalling as mentioned in https://github.com/JeffreyWay/laravel-mix/issues/983#issuecomment-314473998 by @tsndr did the trick for me though.

**Comment by JeffreyWay** [comment]
It looks like the npm repo has fixed the issue, and are about to release a patched version. Gonna close this now.

**Comment by jeff-h** [comment]
I know this is closed, but adding a little info which may help explain why it works for some and not others; I noticed prior to downgrading `npm` from `5.2.0` to `5.1.0` that `5.2.0` had installed various laravel-mix dependencies into a `node_modules` nested *inside* laravel mix. `5.1.0` put these dependencies alongside mix.

So my theory is that things might have been fine for anyone who happened to have the correct dependencies directly inside their root-level node_modules, but those who got them courtesy of laravel-mix would have had them installed in the wrong place.

**Comment by andre-dw** [comment]
Is this fixed with npm version 5.3.0?

**Comment by jeff-h** [comment]
I'll have a try tomorrow first thing.

**Comment by crabmusket** [comment]
This seems to be fixed for me in 5.3.0, after doing a clean and reinstall as per https://github.com/JeffreyWay/laravel-mix/issues/983#issuecomment-314473998

**Comment by unr** [comment]
Confirmed - Latest npm w/ clean reinstall from https://github.com/JeffreyWay/laravel-mix/issues/983#issuecomment-314473998 solved my issues.

**Comment by jeff-h** [comment]
I'll add a me-to (better late than never). Upgraded npm from 5.1 to 5.3 and all is (still) good.

**Comment by patpaskoch** [comment]
same problem node v8.4.0 npm v5.3.0 laravel v5.4.33

`npm i --save-dev babel-loader sass-loader vue-loader solved it for me.`

**Comment by yyc1217** [comment]
same issue, switch to ```yarn``` and it's fixed.

**Comment by antonioribeiro** [comment]
Got the same here, out of the blue, because I did nothing.

So if

``` bash
rm -rf node_modules
yarn
``` 
doesn't work for you

``` bash
rm -rf node_modules
npm install

```
may.

**Comment by yusufabayomio** [comment]
npm install --save-dev babel-loader babel-core babel-preset-env webpack;
npm install --save-dev sass-loader vue-loader

Worked for me

**Comment by ululajib** [comment]
Please help me ...

npm run dev
@ dev /var/www/html/screp
npm run development
@ development /var/www/html/screp
cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
95% emitting

ERROR Failed to compile with 1 errors 00:33:59

This dependency was not found:

/var/www/html/screp/resources/assets/sass/app.scss in multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss
To install it, you can run: npm install --save /var/www/html/screp/resources/assets/sass/app.scss
Asset Size Chunks Chunk Names
/js/app.js 4.12 kB 0 [emitted] /js/app

ERROR in ./resources/assets/js/app.js
Module build failed: ReferenceError: Unknown plugin "transform-object-rest-spread" specified in "base"t > 0, attempted to resolve relative to "/var/www/html/screp/resources/assets/js"
at /var/www/html/screp/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
> at Array.map ()
> at Function.normalisePlugins (/var/www/html/screp/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
> at OptionManager.mergeOptions (/var/www/html/screp/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
> at OptionManager.init (/var/www/html/screp/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
> at File.initOptions (/var/www/html/screp/node_modules/babel-core/lib/transformation/file/index.js:212:65)
> at new File (/var/www/html/screp/node_modules/babel-core/lib/transformation/file/index.js:135:24)
> at Pipeline.transform (/var/www/html/screp/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
> at transpile (/var/www/html/screp/node_modules/babel-loader/lib/index.js:50:20)
> at /var/www/html/screp/node_modules/babel-loader/lib/fs-cache.js:118:18
> at ReadFileContext.callback (/var/www/html/screp/node_modules/babel-loader/lib/fs-cache.js:31:21)
> at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:437:13)
@ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss
ERROR in multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss>
Module not found: Error: Can't resolve 'css-loader' in '/var/www/html/screp'
@ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss

**Comment by Harti** [comment]
@ululajib it looks as if some file is trying to call your app.scss file like a node binary. What you posted is not going to help anyone find out what you did wrong, the error is most likely in one of these files: 

* app.js
* webpack.mix.js 
* webpack.config.js 
* or even package.json

You may want to post contents of these files, or go with copy-pasting the tutorial instructions for the time being. The biggest mistake you can make is overestimate yourself and think you can tweak a new framework "on the fly".

**Comment by nousename** [comment]
On windows 10, fresh install, totally vanilla
I have node 5.6
Have tried the remove, clean reinstall.
Have added from @yusufabayomio the various libraries and am still getting
`> node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

 95% emitting ERROR  Failed to compile with 2 errors20:00:19

These dependencies were not found:

* E:\RobinsonUberspace\src\app.js in multi ./src/app.js ./src/app.scss
* E:\RobinsonUberspace\src\app.scss in multi ./src/app.js ./src/app.scss
`
Any suggestions?

**Comment by nousename** [comment]
Ok, I've just solved this.
The paths were wrong, they should in Laravel 5.5 be
`mix.js('resources/assets/js/app.js', 'public/js')
   .sass('resources/assets/sass/app.scss', 'public/css');`

**Comment by ryanmortier** [comment]
I just upgraded an app from Laravel 5.1 to Laravel 5.7 and I had to change my paths as the previous poster said.

**Comment by Varin6** [comment]
For those coming here in 2019 - I had same issue today, tried everything from this thread and nothing worked. I was gettng this error:

`ERROR in multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss
Module not found: Error: Can't resolve 'D:\' in 'D:\!DEVELOPMENT\Projects\Hercules'
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss`

The solution turned out to be pretty simple. I had to move the project out of the `!DEVELOPMENT` directory due to the "!" sign. I think something doesn't read the path properly because of the exclamation mark. This solved the issue.

**Comment by damayantinama** [comment]
How to resolve this error

ERROR in ./resources/js/app.js
Module not found: Error: Can't resolve 'bootstrap-vue/es/components' in 'E:\xampp\htdocs\pdd\resources\js'
 @ ./resources/js/app.js 30:0-60 33:8-21
 @ multi ./resources/js/app.js ./resources/sass/app.scss ./resources/sass/app-rtl.scss

**Comment by smitpatelx** [comment]
You basically need these dependencies 
```json
"dependencies": {
    "@fortawesome/fontawesome-free": "^5.11.2",
    "axios": "^0.19",
    "cross-env": "^5.1",
    "laravel-mix": "^4.0.7",
    "lodash": "^4.17.13",
    "popper.js": "^1.12",
    "resolve-url-loader": "2.3.1",
    "sass": "^1.20.1",
    "sass-loader": "7.*",
    "vue": "^2.5.17",
    "vue-template-compiler": "^2.6.10"
  },
  "devDependencies": {
    "tailwindcss": "^1.1.2",
    "vue2-transitions": "^0.3.0"
  }
```

**Comment by ThirashaWijerathna** [comment]
finally it's works!!

I run `npm cache clear --force `

**Comment by mohamed-90** [comment]
please do this => npm install laravel-mix@latest
